### ISSUE TITLE
开发环境中无法监听改变

### ISSUE THREAD

**Issue by bingtsingw** [dewfall123/umi-plugin-tailwindcss#13]
我用的是最新的tailwind, 开启了JIT, 在开发环境中, 如果添加了新的class, 插件没有重新编译

**Comment by dewfall123** [comment]
可以参考https://github.com/tailwindlabs/tailwindcss/issues/5132#issuecomment-894549642 或者 [文档](https://tailwindcss.com/docs/just-in-time-mode#styles-don-t-update-when-saving-content-files) 的解决方案
