### ISSUE TITLE
constants.ts 的 tailwindcssContent 缺失 @tailwind base;

### ISSUE THREAD

**Issue by nodegin** [dewfall123/umi-plugin-tailwindcss#17]
导至 transform rotate-45 等无法使用，必须另外新建 css 档

**Comment by dewfall123** [comment]
@tailwind base 只是引入基础样式  https://tailwindcss.com/docs/preflight， 和 transform rotate-45无关吧

另外可以用tailwindCssFilePath自定义 [文档](https://github.com/dewfall123/umi-plugin-tailwindcss/blob/master/README.CN.md#%E9%85%8D%E7%BD%AE)

再另外，umi4内置支持tailwind了，新项目已经不需要此插件了  https://umijs.org/docs/guides/generator#tailwind-css-%E9%85%8D%E7%BD%AE%E7%94%9F%E6%88%90%E5%99%A8
