### ISSUE TITLE
jit模式不生效

### ISSUE THREAD

**Issue by Soundmark** [dewfall123/umi-plugin-tailwindcss#18]
开启jit模式后，jit的特性不生效，原来普通的特性也失效了。

**Comment by dewfall123** [comment]
有自己安装指定版本的tailwindcss吗？ [文档](https://github.com/dewfall123/umi-plugin-tailwindcss/blob/master/README.CN.md#%E8%AF%B4%E6%98%8E)
如果是用的默认的版本或者2.x以下版本，检查项purge配置 [tailwindcss@2文档](https://v2.tailwindcss.com/docs/just-in-time-mode#enabling-jit-mode)

其实umi版本是最新的话，也可以直接安装最新的tailwindcss版本。

最好能有个最小复现仓库。

**Comment by Soundmark** [comment]
版本是2.2.x，purge已经包含了文件目录

最小可复现仓库：https://github.com/Soundmark/umi-tailwindcss-reproduce

**Comment by dewfall123** [comment]
我试了运行这个仓库没问题？
```css
.w-\[40px\] {
    width: 40px;
}
```

**Comment by Soundmark** [comment]
![image](https://user-images.githubusercontent.com/57323166/186065391-a51f988e-0c6a-427e-8b93-e957ae1918b9.png)
按照官方的说法不是不需要自定义类名吗？你这个应该不是jit的用法把。

> > 最小可复现仓库：https://github.com/Soundmark/umi-tailwindcss-reproduce
> 
> 我试了运行这个仓库没问题？
> 
> ```css
> .w-\[40px\] {
>     width: 40px;
> }
> ```

**Comment by dewfall123** [comment]
> ```css
> .w-\[40px\] {
>     width: 40px;
> }
> ```
这个是指运行结果，不是用法。

你用这个链接在线运行下，我试了并不能复现。
https://stackblitz.com/github/Soundmark/umi-tailwindcss-reproduce?file=package.json

**Comment by Soundmark** [comment]
> > ```css
> > .w-\[40px\] {
> >     width: 40px;
> > }
> > ```
> 
> 这个是指运行结果，不是用法。
> 
> 你用这个链接在线运行下，我试了并不能复现。 https://stackblitz.com/github/Soundmark/umi-tailwindcss-reproduce?file=package.json

我懂了，是我的使用姿势不对
