### ISSUE TITLE
启用了插件，IDE怎么没有class提示

### ISSUE THREAD

**Issue by winter-ice** [dewfall123/umi-plugin-tailwindcss#2]

**Comment by dewfall123** [comment]
需要装ide插件  vscode可以用这个 https://marketplace.visualstudio.com/items?itemName=bradlc.vscode-tailwindcss

**Comment by winter-ice** [comment]
IDEA呢？之前写vue 或者传统html项目的时候都会自动提示

**Comment by dewfall123** [comment]
和插件配置有关吧。可能有类似，仅对vue或html文件才**启用**该插件的配置？  

我自己没用IDEA，具体就不清楚了

**Comment by winter-ice** [comment]
好的，感谢回复
