### ISSUE TITLE
每次改一下重新编译时间较长（20s左右）

### ISSUE THREAD

**Issue by arvinxx** [dewfall123/umi-plugin-tailwindcss#4]
基于 Ant Design Pro 做了下尝试，用了 less 文件。

```less
@tailwind utilities;

.test {
  @apply rounded-md bg-white p-4;
}

```

然后每次修改 @apply 里的内容，导致重新编译，用时较长（大约 20s 左右），这个是插件的问题还是 umi 的问题？

**Comment by dewfall123** [comment]
`@tailwind utilities;` 这一行导致的。

插件会自动引入tailwindcss的。如果需要手动定制引入tailwindcss内容，在 `.umirc.ts`或`config\config.ts` 增加tailwindCssFilePath配置即可。

> [2. 将 Tailwind 添加到你的 CSS 代码中。如果tailwindCssFilePath配置存在，会使用该路径的文件。如果缺少，会创建一份临时文件，并引入该临时文件。](https://github.com/dewfall123/umi-plugin-tailwindcss/blob/master/README.CN.md#%E8%AF%B4%E6%98%8E)

**Comment by arvinxx** [comment]
所以不用引入 `@tailwind ` 就直接可以写的意思咯？

**Comment by dewfall123** [comment]
是的

**Comment by arvinxx** [comment]
👌 感谢
