### ISSUE TITLE
存在APP_ROOT环境变量的情况下，tailwind.config.js识别错误导致purge失败

### ISSUE THREAD

**Issue by TIS-OMiddle** [dewfall123/umi-plugin-tailwindcss#7]
electron项目的main、renderer目录结构，因此设置了 `APP_ROOT=src/renderer` 。复现步骤：
- repo url: https://github.com/TIS-OMiddle/umi-electron-demo/tree/dev
- 删除根目录下的`tailwind.config.js`
- `yarn build`

打包输出的css文件引入了全部tailwind样式(2MB+)。但复制一份`tailwind.config.js`到根目录后正常，感觉tailwind是直接读`process.cwd()`了，插件层面应该有办法给tailwincss指定配置文件路径？

**Comment by dewfall123** [comment]
已修复，应该更新下包就好了。 

新增了支持配置tailwindConfigFilePath，默认值如下：
```
tailwindConfigFilePath || join(process.env.APP_ROOT || api.cwd, 'tailwind.config.js')
```
