### ISSUE TITLE
安装失败

### ISSUE THREAD

**Issue by HeliumTang** [dewfall123/umi-plugin-tailwindcss#8]
$ yarn add umi-plugin-tailwindcss -D
yarn add v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] Resolving packages...
[2/4] Fetching packages...
info fsevents@2.3.2: The platform "win32" is incompatible with this module.
info "fsevents@2.3.2" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > @ant-design/pro-layout@6.16.0" has unmet peer dependency "antd@^4.x".
warning "@ant-design/pro-layout > @ant-design/pro-provider@1.4.9" has unmet peer dependency "antd@4.x".
warning "@ant-design/pro-layout > @ant-design/pro-provider@1.4.9" has incorrect peer dependency "react@^16.x".
warning "@ant-design/pro-layout > @ant-design/pro-utils@1.15.2" has unmet peer dependency "antd@4.x".
warning "@ant-design/pro-layout > @ant-design/pro-utils@1.15.2" has incorrect peer dependency "react@^16.x".
warning "@ant-design/pro-layout > use-json-comparison@1.0.5" has incorrect peer dependency "react@16.x".
warning "@ant-design/pro-layout > use-media-antd-query@1.0.6" has incorrect peer dependency "react@16.x".
warning "@umijs/preset-react > @umijs/plugin-layout@0.14.1" has unmet peer dependency "@ant-design/icons@^4.0.0".
warning "@umijs/preset-react > @umijs/plugin-dva > babel-plugin-dva-hmr@0.4.2" has unmet peer dependency "redbox-react@1.x".
warning "@umijs/preset-react > @umijs/plugin-dva > dva@2.6.0-beta.22" has incorrect peer dependency "react@^16.8.4".
warning "@umijs/preset-react > @umijs/plugin-dva > dva@2.6.0-beta.22" has incorrect peer dependency "react-dom@^16.8.4".
warning "@umijs/preset-react > @umijs/plugin-dva > dva-loading@3.0.22" has unmet peer dependency "dva-core@^1.1.0 | ^1.5.0-0 | ^1.6.0-0".
warning "@umijs/preset-react > @umijs/plugin-locale > react-intl@3.12.1" has incorrect peer dependency "react@^16.3.0".
warning "@umijs/preset-react > @umijs/plugin-antd > antd > rc-picker@2.5.10" has unmet peer dependency "dayjs@^1.8.30".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has incorrect peer dependency "react@^16.4.0".
warning "@umijs/preset-react > @umijs/plugin-dva > dva > connected-react-router@6.5.2" has unmet peer dependency "react-router@^4.3.1 || ^5.0.0".
[4/4] Building fresh packages...

success Saved lockfile.
success Saved 28 new dependencies.
info Direct dependencies
└─ umi-plugin-tailwindcss@3.0.3
info All dependencies
├─ @fullhuman/postcss-purgecss@3.1.3
├─ acorn-node@1.8.2
├─ at-least-node@1.0.0
├─ bytes@3.1.0
├─ camelcase-css@2.0.1
├─ color-string@1.5.5
├─ color@3.1.3
├─ css-unit-converter@1.1.2
├─ defined@1.0.0
├─ detective@5.2.0
├─ didyoumean@1.2.1
├─ fs-extra@9.1.0
├─ html-tags@3.1.0
├─ jsonfile@6.1.0
├─ lodash.toarray@4.4.0
├─ modern-normalize@1.0.0
├─ nanoid@3.1.22
├─ node-emoji@1.10.0
├─ object-hash@2.1.1
├─ postcss-functions@3.0.0
├─ postcss-js@2.0.3
├─ postcss-nested@4.2.3
├─ pretty-hrtime@1.0.3
├─ purgecss@3.1.3
├─ reduce-css-calc@2.1.8
├─ simple-swizzle@0.2.2
├─ tailwindcss@2.0.1-compat
└─ umi-plugin-tailwindcss@3.0.3
$ umi generate tmp
Specified Tailwind config file "E:\FrontEnd\typescript-react\umi-tailwind\tailwind.config.js" doesn't exist.
**Error: Specified Tailwind config file "E:\FrontEnd\typescript-react\umi-tailwind\tailwind.config.js" doesn't exist.**
    at _default (E:\FrontEnd\typescript-react\umi-tailwind\node_modules\tailwindcss\lib\lib\registerConfigAsDependency.js:16:11)
    at E:\FrontEnd\typescript-react\umi-tailwind\node_modules\tailwindcss\lib\index.js:85:58
    at creator (E:\FrontEnd\typescript-react\umi-tailwind\node_modules\postcss\lib\postcss.es6:111:34)
    at Object.fn (E:\FrontEnd\typescript-react\umi-tailwind\node_modules\umi-plugin-tailwindcss\dist\index.js:51:13)
    at E:\FrontEnd\typescript-react\umi-tailwind\node_modules\@umijs\core\lib\Service\Service.js:573:37
    at Generator.next (<anonymous>)
    at asyncGeneratorStep (E:\FrontEnd\typescript-react\umi-tailwind\node_modules\@umijs\core\lib\Service\Service.js:108:103)
    at _next (E:\FrontEnd\typescript-react\umi-tailwind\node_modules\@umijs\core\lib\Service\Service.js:110:194)
    at E:\FrontEnd\typescript-react\umi-tailwind\node_modules\@umijs\core\lib\Service\Service.js:110:364
    at new Promise (<anonymous>)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by dewfall123** [comment]
已修复  重新安装下。

**Comment by Taohanxu** [comment]
我安装的时候也遇到这个问题，但是可以正常使用

**Comment by dewfall123** [comment]
有空可以提供个最小仓库，我排查下
